name: SFDC Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sfdc-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SFDC Docker Image
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest

      - name: List files in workspace
        run: ls -R ${{ github.workspace }}

      - name: Verify Salesforce CLI installation
        run: sfdx --version

      - name: Verify Salesforce CLI plugins
        run: sfdx plugins --core
        