name: SFDC Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sfdc-job:
    runs-on: ubuntu-latest
    container: njyoon/sfdc:latest
    env:
      SFDC_USERNAME: ${{ secrets.SFDC_USERNAME }}
      SFDC_CLIENT_ID: ${{ secrets.SFDC_CLIENT_ID }}
      SFDC_CLIENT_SECRET: ${{ secrets.SFDC_CLIENT_SECRET }}
      SFDC_CERTIFICATE_KEY: ${{ secrets.SFDC_CERTIFICATE_KEY }}
      SFDC_INSTACE_URL: ${{ secrets.SFDC_INSTACE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write certificate key to file
        run: echo "$SFDC_CERTIFICATE_KEY" > ${{ github.workspace }}/server.key


      - name: List files in workspace
        run: |
          ls -R ${{ github.workspace }}


      - name: Verify Salesforce CLI installation
        run: |
          sf --version

      - name: Authenticate with Dev Hub
        run: |
          sf org login jwt --client-id $SFDC_CLIENT_ID \
          --jwt-key-file ${{ github.workspace }}/server.key --username $SFDC_USERNAME \
          --instance-url $SFDC_INSTACE_URL --alias my-hub-org --set-default-dev-hub

      - name: Create Scratch ORG
        run: |
          sf org create scratch --definition-file ${{ github.workspace }}/config/project-scratch-def.json --set-default --alias test-org -v my-hub-org

      - name: Deploy to Scratch ORG
        run: |
          sf project deploy start -w 60 -o test-org
