name: SFDC Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sfdc-job:
    runs-on: ubuntu-latest
    env:
      SFDC_USERNAME: ${{ secrets.SFDC_USERNAME }}
      SFDC_CLIENT_ID: ${{ secrets.SFDC_CLIENT_ID }}
      SFDC_CLIENT_SECRET: ${{ secrets.SFDC_CLIENT_SECRET }}
      SFDC_CERTIFICATE_KEY: ${{ secrets.SFDC_CERTIFICATE_KEY }}
      SFDC_INSTACE_URL: ${{ secrets.SFDC_INSTACE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write certificate key to file
        run: echo "$SFDC_CERTIFICATE_KEY" > server.key

      - name: Run SFDC Docker Image
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest

      - name: List files in workspace
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest ls -R ./workspace


      - name: Verify Salesforce CLI installation
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest sfdx --version

      - name: Authenticate with Dev Hub
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest sf org login jwt --client-id $SFDC_CLIENT_ID \
          --jwt-key-file ./workspace/server.key --username $SFDC_USERNAME \
          --instance-url $SFDC_INSTACE_URL --alias my-hub-org --set-default-dev-hub

      - name: Create Scratch ORG
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest sf org create scratch --definition-file ./workspace/config/project-scratch-def.json --set-default --alias test-org

      - name: Deploy to Scratch ORG
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace njyoon/sfdc:latest sf project deploy start -w 60
